# https://taskfile.dev

version: '3'

vars:
  VERSION: v1.0.0
  LDFLAGS: "-X main.buildVersion={{.VERSION}} -X main.buildDate={{ now | date \"2006-01-02\" }} -X main.buildCommit=$COMMIT"

tasks:
  build:
    cmds:
      - |
        export COMMIT=$(git rev-parse --short HEAD)
        go build -ldflags "{{.LDFLAGS}}" ./cmd/gophkeeper/.
    silent: true
