# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install timezone dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tzdata
        ls -la $(go env GOROOT)/lib/time/zoneinfo.zip

    - name: Test
      run: task test

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: iwakho/gopherkeep
        threshold-total: 50
    
        ## when token is not specified (value '') this feature is turned off
        ## in this example badge is created and committed only for main branch
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        ## name of branch where badges are stored
        ## ideally this should be orphan branch (see below how to create this branch)
        git-branch: badges
